[해나] 회원가입 미션 1, 2단계 제출합니다.
woowacourse/android-signup pull request #15
Opened 2024-10-11 06:36 UTC by hxeyexn

안녕하세요 오둥이! 오랜만이네요 🥹
Compose는 처음이라 어렵네요 ㅎㅎ
리뷰 잘 부탁드리겠습니다!!

### Composable 함수를 분리하는 기준
Composable 함수를 분리하는 기준을 고민하다가 아래와 같이 xml에서 style을 정의하는 기준으로 분리해보려 했습니다!
Composable 함수 분리도 재활용을 위한 거라고 생각해서 style과 비슷하다는 생각이 들었어요!!

```xml
    <style name="ButtonStyle">
        <item name="android:layout_width">0dp</item>
        <item name="android:layout_height">wrap_content</item>
        <item name="android:minWidth">0dp</item>
        <item name="android:minHeight">0dp</item>
        <item name="android:paddingVertical">14dp</item>
        <item name="android:stateListAnimator">@null</item>
        <item name="android:textAppearance">@style/Typography.Title3</item>
    </style>
```

오둥이는 어떤 기준으로 분리했는지도 궁금하네요!

2024-10-11 09:06 UTC, murjune requested changes
안녕하세요 해나! 1, 2 단계 미션 요구사항을 빠르게 잘 구현해주셨네요 👏  
해나와 함께 고민해봤으면 좋겠는 점을 코멘트로 남겼으니 곰곰히 생각하고 답글 달아주세요~!~!

2024-10-11 09:06 UTC, murjune commented on gradle/libs.versions.toml
> +ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
ktLint도 하셨네요 💯 (난 안했는데..)

2024-10-11 09:06 UTC, murjune commented on gradle/libs.versions.toml
> +agp = "8.3.1"
agp 를 다운시킨 이유가 있으실까요!

2024-10-11 09:06 UTC, murjune commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +fun ButtonView(
View 와 Compose 를 동시에 사용하는 프로젝트에서 컴포저블 함수가 `xxxView` 라는 네이밍이라면 헷갈릴 것 같아요!
따라서, 저는 기존 전통 View 시스템과의 구분을 위해 Compose 에서는 `View` 라는 일반적으로 postfix 를 사용하지 않습니다.

2024-10-11 09:06 UTC, murjune commented on app/src/main/java/nextstep/signup/MainActivity.kt
> +                    color = MaterialTheme.colorScheme.background,
Surface 는 기본적으로 `MaterialTheme.colorScheme.surface` 로 지정되어있습니다!

`MaterialTheme.colorScheme.background` 로  color 를 바꿔주신 이유가 따로 있으실까요??

2024-10-11 09:06 UTC, murjune commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +fun TextView(
마찬가지로 XML TextView 와 헷갈릴 수 있을 것 같습니다!

2024-10-11 09:06 UTC, murjune commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +fun TextView(
저는 StringRes 보다는 String 으로 값을 넘기는걸 선호합니다!   
StringRes 의 경우 정적이기 때문에 동적으로 String 이 변환돼서 온다면 이를 해결할 방법이 없기 때문입니다.

예시를 들어볼게요!
만약, ViewModel 에서 userName을 보내주고 TextView 에서 userName를 보여주고 싶다고 해봅시다. 그런데 description 가 StringRes 라 표시해줄 방법이 없겠네요 😢

TextView 의 경우 더더욱 기본 컴포넌트이기에 다른 컴포넌트에 비해 훨씬 유연성이 높아야한다고 생각해요! 따라서, String 타입으로 변경하는걸 제안드립니다 💪

2024-10-11 09:06 UTC, murjune commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +    paddingTop: Dp = 0.dp,
보통 paddingTop 과 같은 세부사항을 직접 넘기지 않고 `Modifier` 를 설정하고 넘겨줍니다!  

Modifier를 사용하여 좀 더 유연하게 UI 설정을 할 수 있어요!
```suggestion
    modifier: Modifier = Modifier,
```

근데 `Modifer` 의 역할이 무엇일까요??

2024-10-11 09:06 UTC, murjune commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +    paddingTop: Dp = 0.dp,
위와 마찬가지로 `TextFieldView` 는 네이밍에서 유추해본다면 프로젝트 전역에서 사용할 수 있는 기본 컴포넌트라는 생각이 들어요.

그래서, `SignUpTextField` 로 네이밍 변경 제안드려봅니다 🤔

2024-10-11 09:06 UTC, murjune commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +    var input by remember { mutableStateOf("") }
TextView 가 직접 상태를 관리하는 대신 부모로 상태를 올려볼까요? 이를 [상태 호이스팅](https://developer.android.com/develop/ui/compose/state-hoisting?hl=ko)기법이라 합니다.

질문1)  왜 상태 호이스팅을 해야할까요??
질문2) StateLess 컴포저블과 StateFull 컴포저블의 차이는 뭘까요? 

힌트) 만약 유저 정보를 사용자에게 입력받아 서버로 보내려면 어떻게 해야될까요? 🤔

2024-10-11 09:06 UTC, murjune commented on app/src/main/java/nextstep/signup/MainActivity.kt
> +    TextFieldView(paddingTop = 36.dp, label = R.string.main_password, keyboardType = KeyboardType.Password)
KeyboradType 을 잘 바꿔주셨네요. 저는 Email 타입도 지정 안했는데 덕분에 알아갑니다 👍👍👍

2024-10-11 09:06 UTC, murjune commented on app/src/main/java/nextstep/signup/MainActivity.kt
>  fun GreetingPreview() {
Preview 의 경우 private 키워드 붙이는 걸 제안드립니다! 다른 파일에서 해당 Preview를 참조할 수 있으면 안되겠죠? 😉

```suggestion
private fun SignUpScreenPreview() {
```

2024-10-11 09:06 UTC, murjune commented on app/src/main/java/nextstep/signup/MainActivity.kt
> +                        ButtonView(R.string.main_sign_up, paddingTop = 42.dp)
보통 Screen 은 화면 단위에 붙이는 네이밍이에요! 그러나 현재 Fragment? 같은 느낌으로 사용되고 있네요  

화면 단위로 리팩토링해볼까요?

2024-10-11 09:06 UTC, murjune commented on app/src/main/java/nextstep/signup/MainActivity.kt
> +                        ButtonView(R.string.main_sign_up, paddingTop = 42.dp)
그리고, TextFieldScreen 보다는 SignUpScreen 이란 네이밍은 어떠신가요!

2024-10-11 09:06 UTC, murjune commented on app/src/androidTest/java/nextstep/signup/LayoutBasicsTest.kt
> +class LayoutBasicsTest {
1단계를 완벽하게 수행해주셨네요!

2024-10-11 09:27 UTC, murjune commented
> Composable 함수를 분리하는 기준
Composable 함수를 분리하는 기준을 고민하다가 아래와 같이 xml에서 style을 정의하는 기준으로 분리해보려 했습니다!
Composable 함수 분리도 재활용을 위한 거라고 생각해서 style과 비슷하다는 생각이 들었어요!!

    <style name="ButtonStyle">
        <item name="android:layout_width">0dp</item>
        <item name="android:layout_height">wrap_content</item>
        <item name="android:minWidth">0dp</item>
        <item name="android:minHeight">0dp</item>
        <item name="android:paddingVertical">14dp</item>
        <item name="android:stateListAnimator">@null</item>
        <item name="android:textAppearance">@style/Typography.Title3</item>
    </style>
> 오둥이는 어떤 기준으로 분리했는지도 궁금하네요!

저는 개인적으로 style 과 Component 는 별개라고 생각합니다!
CustomView 와 Component 를 비슷한 선상에서 보고 있습니다 😁  
Compose 에서도 `Theme.kt` 에서 ButtonStyle 과 같이 style을 따로 정의해줄 수 있습니다.  

---

저는 Composable 함수를 3가지 관점에서 분리하고 있어요

1. 기본 컴포넌트 

다자인 일관성이 중요한 프로젝트에서만 정의하는데요 (디자이너가 해줘야하지만..)
프로젝트 전역에서 사용하는 `기본 컴포넌트`이기에 최대한 공통되는 부분만 Composable 내에 정의해두고  
세부 사항의 경우에는 외부에서 주입받는 형태로 최대한 변경에 유연하게 대처할 수 있도록 구현합니다.


2. 조금 더 큰 컴포넌트

이걸 뭐라해야할지 모르겠는데요.. 기본 컴포넌트를 조합한 컴포넌트를 뜻합니다.  
만약, 특정 기능 예를 들어 `포켓몬 도감` 기능에서만 사용하는 컴포넌트의 경우 `포켓몬`이라는 특성에 초점을 맞춰 설계하는 것 같아요.  
기본 컴포넌트보다는 좀 더 세부 구현 사항을 컴포넌트 함수 및 시그니처에 정의해요 

3. 해당 화면에서만 사용하는 컴포넌트

그렇게, 신경써서 설계하지 않습니다 ㅋㅋㅋㅋ 어차피 여기서만 쓰겠지~ 라는 마인드로 StateLess 와 가독성에 초점을 맞춰 설계해요 ㅎㅎ  

--- 

뭔가 제 컴포넌트 설계 방식을 글로 정리해본적이 없어서... 잘 전달될지 모르겠어요 😅  
조금 더 생각해보고 정리해서 다시 전달드릴게욥

2024-10-12 05:54 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +fun ButtonView(
View 와 Compose 를 동시에 사용하는 프로젝트는 고려해보지 못했네요..! xml을 이용한 프로젝트를 compose로 리팩터링한다면 ㅌ`xxxView` 라는 네이밍이 헷갈릴 수 있겠네요~ 다른 네이밍 고민해보겠습니다!

2024-10-14 06:42 UTC, murjune commented
@hxeyexn 

개인적으로 컴포넌트 설계도 class 설계와 거의 똑같다고 생각하고 있습니다.  

> 모든 UI를 변화 대처에 용이한 컴포넌트로 분리할 필요가 있을까?? == `1 기능을 1 Class로 분리해야할까?`

즉, 자주 바뀔 수 있는 부분만 확장성을 고려하여 설계하고, 크게 바뀌지 않을 부분에는 빠르게 구현하는데 집중해서 개발하고 있습니다.
컴포즈의 모든 컴포넌트 설계를 3가지 방식만 으로 정할 수 없지만, 저는 다음과 같은 생각을 가지고 컴포넌트를 분리하고 있어요.


1. 기본 컴포넌트 

다자인 일관성이 중요한 프로젝트에서만 정의하는데요 (팀원들도 모두 동의하고 디자이너가 해줘야하지만..)
프로젝트 전역에서 사용하는 `기본 컴포넌트`이기에 최대한 공통되는 부분만 Composable 내에 정의해두고  
세부 사항의 경우에는 외부에서 주입받는 형태로, 최대한 변경에 유연하게 대처할 수 있도록 [Slot api](https://kofathena.tistory.com/m/114) 형태로 설계합니다.

```kotlin
// 다른 프로젝트에서 사용했던 걸 재구성해보았어요
@Composable
fun PokeChip(
    modifier: Modifier = Modifier,
    matched: Boolean = false,
    selected: Boolean,
    enabled: Boolean,
    onSelected: () -> Unit = {},
    shape: CornerBasedShape = PokeTheme.shapes.medium,
    label: @Composable () -> Unit,
    leadingIcon: @Composable (() -> Unit)? = null,
    trailingIcon: @Composable (() -> Unit)? = null,
    colors: PunchChipColors = PokeChipColors(),
    interactionSource: MutableInteractionSource = remember { MutableInteractionSource() }
)
```

2. 조금 더 큰 컴포넌트

기본 컴포넌트를 조합한 컴포넌트를 뜻합니다.  
만약, 특정 기능 예를 들어 `포켓몬 도감` 기능에서만 사용하는 컴포넌트의 경우 `포켓몬`이라는 특성에 초점을 맞춰 설계하는 것 같아요.  
기본 컴포넌트보다는 좀 더 세부 구현 사항을 컴포넌트 함수 및 시그니처를 설계해요.

```kotlin
// 여러 기본 컴포넌트를 조합함
@Composable
fun Pokemon(modifier: Modifier = Modifier, pokemon: Pokemon, ...) {
       Surface(modifier) {
               Box(..) {
                   Image(...)
                   PokemonType(..)
                   Spacer(...)
                   Text(...)
               }
       }
}
```

3. 해당 화면에서만 사용하는 컴포넌트

> viewModel 에서 가독성을 위해 `private fun` 로 함수화한다는 느낌과 비슷합니다

그렇게, 신경써서 설계하지 않습니다 ㅋㅋㅋㅋ 어차피 여기서만 쓰겠지~ 라는 마인드로 Stateless 와 가독성에 초점을 맞춰 설계해요 ㅎㅎ  

---

생각을 정리한다고 했는데, 쉽지 않네요.. 해나 덕분에 스스로 생각을 정리하는 시간을 갖게 된거 같아요 땡큐 😉

2024-10-14 07:02 UTC, woowahan-leah commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +    var input by remember { mutableStateOf("") }
@murjune 선생님 진도가 너무 빠릅니다

2024-10-15 12:56 UTC, hxeyexn commented on gradle/libs.versions.toml
> +agp = "8.3.1"
지금 사용하고 있는 android studio의 버전이 Iguana라서 agp 8.5.1이랑은 호환되지 않는 문제가 있었습니다.

<img width="794" alt="image" src="https://github.com/user-attachments/assets/708e0ad9-3481-4ee2-bb78-add05228203c">

해결 방법을 찾는 과정에서 agp 버전 다운그레이드와 안드로이드 스튜디오 버전 업데이트 두가지를 고려해봤습니다.

우선 협업 여부를 고려해봤는 데 이번 미션은 혼자 진행하는 작업이기 때문에 agp를 다운그레이드하더라도 큰 위험이 없다고 판단했습니다.

현재의 상황에서는 안드로이드 스튜디오 버전을 업데이트해서 발생하는 다른 프로젝트들과의 호환성 문제나 최신 버전의 불안정성 문제가  더 해결하기 어렵다고 생각해 agp를 다운그레이드했습니다!

만약 팀 프로젝트였다면 android studio의 버전을 높이는 방법을 선택했을 것 같아요~

2024-10-15 20:59 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +fun TextView(
헉 그렇네요..! 현재 text 컴포저블 함수는 동적으로 변하는 문자는 표시해줄 수 없겠네요!!
`description`의 타입을 `String`으로 변경했습니다! 좋은 예시 감사합니다 👍 

**반영 커밋** : [50d7930](https://github.com/woowacourse/android-signup/pull/15/commits/50d793035325dc651b32592cc8df0b1f9cabd6e0)

2024-10-15 21:10 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/MainActivity.kt
> +                    color = MaterialTheme.colorScheme.background,
우선 미션 초기 셋팅에 `MaterialTheme.colorScheme.background`가 기본으로 설정되어 있었습니다!

`ColorScheme.kt`

<img width="609" alt="image" src="https://github.com/user-attachments/assets/9c6e726c-32b4-4eba-a501-6f879cf9b88b">
<img width="704" alt="image" src="https://github.com/user-attachments/assets/38446204-34a4-4bc0-89a6-a88ac01cef10">

<br>
<br>

`MaterialTheme.colorScheme.surface` 는 카드, 메뉴, 시트 등과 같이 특정 ui 컴포넌트의 배경을 설정해주는 속성이라고 이해했고, `MaterialTheme.colorScheme.background` 전체 화면의 배경을 설정해주는 속성이라고 이해했습니다.

현재 Surface가 회원가입 화면의 최상단 레이아웃 역할을 하고 있다고 생각해서 `MaterialTheme.colorScheme.background`로 설정하는 것이 더 적합하다고 판단했습니다!

2024-10-15 21:14 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/MainActivity.kt
>  fun GreetingPreview() {
private 키워드 추가했습니다!!

`반영 커밋` : [ee57356](https://github.com/woowacourse/android-signup/pull/15/commits/ee5735674dd02a236f7f2a03b30ee81cd7a1f2f8)

2024-10-16 01:58 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/MainActivity.kt
> +                        ButtonView(R.string.main_sign_up, paddingTop = 42.dp)
화면 단위로 리팩터링하는 게 좋겠네요! 리팩터링 내용에 따라 네이밍도 `SignUpScreen`으로 변경했습니다~

`반영 커밋` : [67c63e9](https://github.com/woowacourse/android-signup/pull/15/commits/67c63e91d5d0d709c6845ec8b93f6766a7d8785b)

2024-10-16 02:05 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +fun ButtonView(
`View` 대신 `Component`로 변경했습니다!

`반영 커밋` : [70bfab8](https://github.com/woowacourse/android-signup/pull/15/commits/70bfab89682421f9e86b1c74f5efbc92e4ed1903)

2024-10-16 02:07 UTC, hxeyexn commented on gradle/libs.versions.toml
> +ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
> (난 안했는데..)

어라 ㅋㅋㅋ 오둥이가 compose lint 하는 방법 알려 주셨잖아요 🤣

2024-10-16 02:14 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +fun ButtonView(
전역적으로 사용할 수 있다는 것을 나타내고 싶어서 `GlobalComposable` 로 변경했습니다! 

`반영 커밋` : [577203f](https://github.com/woowacourse/android-signup/pull/15/commits/577203f5d86d95e083df02df817cabe7714a4324)

2024-10-16 04:14 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +    var input by remember { mutableStateOf("") }
> 왜 상태 호이스팅을 해야할까요?

A 라는 컴포저블이 있다고 할 때 어떤 변수를 외부에서 읽거나 수정해야한다면 상태 호이스팅을 해야합니다. 

사용자가 입력한 유저 정보를 서버에 보내야 한다면, 입력된 정보는 ViewModel이 기억하고 있을 겁니다. 상태는 상태가 소비되는 위치에서 가장 가까운 곳에 유지해야 하기 때문에 부모 컴포저블 내부에 상태가 존재해야 합니다. 

A 컴포저블 내부에서만 읽고 수정되는 경우에는 상태 호이스팅을 해도 별다른 이익이 없습니다.

(아직 정확히는 잘 모르겠네요,, 좀 더 공부해보겠습니다 🥹)
<br>

> StateLess 컴포저블과 StateFull 컴포저블의 차이는 뭘까요?

`StateLess Composable`

- StateLess 컴포저블은 아래와 같이 상태를 들고 있는 컴포저블입니다! 
```kotlin
@Composable
private fun UserNameComposable() {
    var userName by remember { mutableStateOf("") }
    TextFieldComponent(userName, onValueChange = { userName = it }, label = R.string.main_user_name)
    Spacer(modifier = Modifier.size(36.dp))
}
```

`StateFull Composable`

- StateFull 컴포저블은 상태를 받아서 뷰를 노출하는 컴포저블입니다! 즉, 상태를 직접적으로 들고 있지 않습니다.
```kotlin
@Composable
fun TextFieldComponent(
    newValue: String,
    onValueChange: (String) -> Unit,
    @StringRes label: Int,
    keyboardType: KeyboardType = KeyboardType.Text,
) {
    TextField(
        value = newValue,
        onValueChange = { onValueChange(newValue) },
        modifier = Modifier.fillMaxWidth(),
        label = { Text(text = stringResource(id = label)) },
        keyboardOptions = KeyboardOptions(keyboardType = keyboardType),
        colors = TextFieldDefaults.colors(focusedIndicatorColor = Blue50),
    )
}
```

2024-10-16 04:35 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +    paddingTop: Dp = 0.dp,
세부사항이 아닌 Modifier를 컴포넌트의 매개변수로 넘겨주는 방식으로 변경했습니다!

`반영 커밋` : [0e79343](https://github.com/woowacourse/android-signup/pull/15/commits/0e7934331678431e823c3f43eb2b1b998e40730c)

2024-10-16 04:39 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +    paddingTop: Dp = 0.dp,
> Modifer 의 역할이 무엇일까요??

Modifier는 Composable의 모양과 동작을 유연하게 변경할 수 있게 도와줍니다. Modifier를 이용해 모양, 패딩, 클릭 이벤트 등을 유연하게 설정할 수 있습니다!

<img width="652" alt="image" src="https://github.com/user-attachments/assets/18a92d24-d212-4207-afbc-a418b6e327f7">

2024-10-16 04:48 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +    paddingTop: Dp = 0.dp,
> 위와 마찬가지로 TextFieldView 는 네이밍에서 유추해본다면 프로젝트 전역에서 사용할 수 있는 기본 컴포넌트라는 생각이 들어요.
>
> 그래서, SignUpTextField 로 네이밍 변경 제안드려봅니다 🤔

TextField는 회원가입 페이지 뿐만 아니라 충분히 다른 화면에서 재활용할 확률이 높다고 생각합니다. 

저희 팀 프로젝트를 예시로 들어보면 TextField를 활용하는 화면이 6개 정도 있습니다! 그래서 TextField를 기본 컴포넌트라고 생각해 SignUp이라는 단어를 넣지 않고 프로젝트 전역에서 사용할 수 있도록 TextFieldView(현 TextFieldComponent)로 네이밍 했습니다.

2024-10-16 04:54 UTC, hxeyexn commented
> 생각을 정리한다고 했는데, 쉽지 않네요..

너무 잘 정리해주셔서 정말 큰 도움이 되었습니다!! 
컴포즈가 처음이라 감이 잘 안 잡혔는 데 오둥이 덕에 컴포넌트를 설계하는 저만의 기준을 조금씩  잡아가고 있는 것 같아요!

> 해나 덕분에 스스로 생각을 정리하는 시간을 갖게 된거 같아요 땡큐 😉

제가 감사하죠 ㅠㅠ 🥹🙇‍♂️

2024-10-16 04:54 UTC, hxeyexn commented
안녕하세요 오둥이!!
프로젝트 이슈 때문에 리뷰 반영이 많이 늦었습니다 ㅠㅠ

컴포넌트 설계에 대한 오둥이의 생각을 잘 정리해주셔서 컴포넌트 설계 방식에 대한 감을 조금씩 잡아가고 있는 것 같습니다..!
생각해볼만한 리뷰도 많이 남겨주셔서 큰 도움이 되었어요!! 👍

정말 감사합니다!! 저도 컴포넌트 설계에 대해서 감을 조금 더 잡게 되면 글로 정리해서 공유해보겠습니다!!

2024-10-16 08:46 UTC, murjune commented on gradle/libs.versions.toml
> +ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
그러게요.. ㅋㅋㅋㅋㅋㅋㅋ

2024-10-16 09:07 UTC, murjune approved these changes
이전보다 훨씬 코드가 유연해졌네요! 👏👏  
제가 질문을 많이 달아서 step 1 미션이 힘드셨을텐데, 고생하셨습니다 ㅎ ㅎ
이번에 남긴 코멘트는 다음 step 3, 4 미션에 함께 적용해주셔요~!!  
step 3,4 도 화이팅입니다 😉

2024-10-16 09:07 UTC, murjune commented on app/src/main/java/nextstep/signup/ui/GlobalComponent.kt
동료 개발자가 GlobalComponent 라는 네이밍만으로는 어떤 전역 컴포넌트가 있는지 파악하기 힘들 것 같아요!
GlobalComponent 보다는 `ButtonComponent`, `TextComponent`.. 등 컴포넌트 별로 파일 분리해주시면 좋을 것 같습니당~   
프리뷰도 작성해주시면 좋을 것 같아요 💪

2024-10-16 09:07 UTC, murjune commented on app/src/main/java/nextstep/signup/MainActivity.kt
> +                    color = MaterialTheme.colorScheme.background,
합당한 이유 좋습니다!  👍👍  
다만,`Surface` 컴포넌트를 사용하셨는데 `colorScheme.surface` 를 사용하는 것이 의미적으로도 더 이해하기 쉽지 않을까요?! 🤔

2024-10-16 09:07 UTC, murjune commented on app/src/main/java/nextstep/signup/ui/GlobalComponent.kt
> +    @StringRes label: Int,
```suggestion
    label: String,
```

https://github.com/woowacourse/android-signup/pull/15#discussion_r1796641918

String 타입으로 바꿔주시면 좋을 것 같습니다!

2024-10-16 09:07 UTC, murjune commented on app/src/main/java/nextstep/signup/ui/GlobalComponent.kt
> +    @StringRes description: Int,
222

https://github.com/woowacourse/android-signup/pull/15#discussion_r1796641918

String 타입으로 바꿔주시면 좋을 것 같습니다!

2024-10-16 09:07 UTC, murjune commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +    paddingTop: Dp = 0.dp,
> 저희 팀 프로젝트를 예시로 들어보면 TextField를 활용하는 화면이 6개 정도 있습니다! 그래서 TextField를 기본 컴포넌트라고 생각해 SignUp이라는 단어를 넣지 않고 프로젝트 전역에서 사용할 수 있도록 TextFieldView(현 TextFieldComponent)로 네이밍 했습니다.

합당한 이유 좋습니다 👍👍👍
이전보다 변경에 훨씬 유연하게 대처할 수 있도록 바꿔주셔서 재사용성이 훨씬 올라갔군요!

2024-10-16 09:07 UTC, murjune commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +    var input by remember { mutableStateOf("") }
> StateLess 컴포저블은 아래와 같이 상태를 들고 있는 컴포저블입니다!
> StateFull 컴포저블은 상태를 받아서 뷰를 노출하는 컴포저블입니다! 즉, 상태를 직접적으로 들고 있지 않습니다.

StateLess 는 상태를 들고 있지 않고, StateFull 은 상태를 들고 있는 컴포저블입니당~

아직 배우지 않은 개념인데 제가 리뷰를 남겨서 해나의 학습에 차질이 있었을 것 같아요 ㅜㅜ  
공부하시느라 고생하셨습니다 😢

2024-10-16 09:07 UTC, merged

2024-10-16 10:08 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/ui/ViewComposable.kt
> +    var input by remember { mutableStateOf("") }
@murjune 

헉 작성하고 정리하는 중에 순서를 잘못 바꿨네요 ㅠㅠㅠ
아래와 같이 수정했습니다!

>StateFull 컴포저블은 아래와 같이 상태를 들고 있는 컴포저블입니다!
>StateLess 컴포저블은 상태를 받아서 뷰를 노출하는 컴포저블입니다! 즉, 상태를 직접적으로 들고 있지 않습니다.

2024-10-16 10:17 UTC, hxeyexn commented
@murjune 

>> StateLess 컴포저블은 아래와 같이 상태를 들고 있는 컴포저블입니다!
StateFull 컴포저블은 상태를 받아서 뷰를 노출하는 컴포저블입니다! 즉, 상태를 직접적으로 들고 있지 않습니다.
>
> StateLess 는 상태를 들고 있지 않고, StateFull 은 상태를 들고 있는 컴포저블입니당~
>
> 아직 배우지 않은 개념인데 제가 리뷰를 남겨서 해나의 학습에 차질이 있었을 것 같아요 ㅜㅜ
> 공부하시느라 고생하셨습니다 😢

<br>

헉 작성하고 정리하는 중에 순서를 잘못 바꿨네요 ㅠㅠㅠ
아래와 같이 수정했습니다!

>StateFull 컴포저블은 상태를 들고 있는 컴포저블입니다!
>StateLess 컴포저블은 상태를 받아서 뷰를 노출하는 컴포저블입니다! 즉, 상태를 직접적으로 들고 있지 않습니다.