[오둥이] 회원가입 미션 1, 2단계 제출합니다.
woowacourse/android-signup pull request #17
Opened 2024-10-11 07:50 UTC by murjune

빙티 안녕하세요~!! 저번에는 리뷰어였넨 관계가 역전(ioc)됐네요 😉  
잘 부탁드림둥~

## Step 1

컴포즈 학습 테스트

- [x] LayoutBasicsTest 의 테스트를 모두 성공 시킨다.
- [x] Preview를 노출시킨다.
- [x] Preview의 interactive 모드를 활용하여 버튼을 클릭해본다.

## Step 2

- [x] Colors, colorScheme 를 정의한다.
- [x] 기본 SignUpTextField 를 만든다.
- [x] UserName, Email, Password, Password Confirm TextField를 화면에 배치한다.
- [x] 화면 밖에 터치하면 focus clear 되도록 한다.
- [x] Password 와 Password Confirm 는 PassWord KeyBoard Options 를 준다.
- [x] SignUp 버튼을 화면에 배치한다.
- [x] rememberSaveable 을 사용하여 회원가입 폼 상태를 저장한다.

## 시연 영상

https://github.com/user-attachments/assets/0bed28fa-b766-4792-b570-4584abc4442a

2024-10-12 15:42 UTC, s6m1n approved these changes
오둥이 1단계 미션을 잘 구현하고 테스트까지 추가해주셨네요~!
제가 아직 Compose에 익숙하지 않아서 궁금한 부분들에 코멘트 남겼습니다..ㅎㅎ
답변 달아주시면 머지하고 다음 단계로 넘어갈게요!

2024-10-12 15:42 UTC, s6m1n commented on app/src/androidTest/java/nextstep/signup/study/LayoutBasicsTest.kt
> +            .onChildAt(0)
`onChildAt`으로도 검사할 수가 있군요?!👍
기왕 테스트에 then을 추가하신 거... Composable들을 분리하고 각각 Preview를 만들어 보는 건 어떨까요!
> LMS 요구사항 : 힌트를 참고하여 Preview를 노출시킨다.

2024-10-12 15:42 UTC, s6m1n commented on app/src/androidTest/java/nextstep/signup/study/LayoutBasicsTest.kt
> +@Preview(showBackground = true, backgroundColor = 0xFFFFFFFF, device = Devices.PIXEL_4_XL)
오둥이가 `device = Devices.PIXEL_4_XL` 옵션을 추가하신 이유가 궁금해요!

2024-10-12 15:42 UTC, s6m1n commented on app/src/main/java/nextstep/signup/ui/theme/Theme.kt
> +    onError = Red20
darkColorScheme도 정의해주셨군요!
`background`와 `surface`의 쓰임새는 어떻게 다를까요?
그리고 기존의 secondary, tertiary와 차이점은 뭘까요?

2024-10-12 15:42 UTC, s6m1n commented on app/src/main/java/nextstep/signup/auth/component/AuthTextField.kt
> +internal fun AuthTextField(
회원가입 프로젝트에 app 모듈만 존재하고 있는데 `internal` 키워드를 사용하신 이유가 궁금합니다!

2024-10-12 15:42 UTC, s6m1n commented on app/src/main/java/nextstep/signup/auth/component/AuthTextField.kt
> +internal fun AuthTextField(
AuthTextField를 오버로드 해주셨네요!
중복을 줄이기 위해 하나의 AuthTextField로 통합하는 건 어떨까요?

2024-10-12 15:42 UTC, s6m1n commented on app/src/androidTest/java/nextstep/signup/auth/screen/SignUpScreenTest.kt
> +}
ktLint를 적용해주세요!

2024-10-12 15:42 UTC, s6m1n commented on app/src/main/java/nextstep/signup/auth/component/AuthTextField.kt
> +@Preview(name = "onClearFocus")
Preview 메서드를 각 케이스 별로 꼼꼼하게 작성해주셨네요!👍
오둥이는 Preview 메서드가 어디에 위치하는 게 적절하다고 생각하시나요?
Compose에서는 보통 @Composable 메서드와 @Preview 메서드를 같은 파일 안에 두는 것 같더라구요!
Composable에 수정이 일어났을 때 실시간으로 변경 사항을 확인할 수 있어서 그런 것 같은데,
이렇게 Preview 메서드의 수가 많은 경우에도 동일한 파일에 위치 시키는지 궁금하네요💭

2024-10-12 15:42 UTC, s6m1n commented on app/src/main/java/nextstep/signup/auth/component/SignUpForm.kt
> +    Spacer(modifier = Modifier.height(16.dp))
저는 constraintLayout에 익숙해서 Modifier에 padding을 명시해 composable 사이의 간격을 조절해 주었는데
오둥이는 Spacer 컴포넌트를 추가해주셨군요?.? 둘 중에 어떤 방법을 더 선호하시는 지 궁금합니다!

2024-10-12 15:42 UTC, s6m1n commented on app/src/main/java/nextstep/signup/ui/interaction/ClearFocus.kt
> +        LaunchedEffect(key1 = Unit) {
꼼꼼한 키보드 숨김 처리 굿~👍
이 부분에서 SideEffect 대신 LaunchedEffect를 사용하신 이유가 궁금합니다!

2024-10-13 02:19 UTC, s6m1n requested changes
RC를 안해서 알림이 안 갔네요..😅

2024-10-14 08:00 UTC, murjune reviewed
@s6m1n 안녕하세요 빙티! 남겨주신 코멘트에 제 생각을 남겨보았어요~  
의문이 생기는 점이 있다면 언제든지 질문 남겨주시면 감사하겠습니다 😉

2024-10-14 08:00 UTC, murjune commented on app/src/androidTest/java/nextstep/signup/auth/screen/SignUpScreenTest.kt
> +}
ktLint 적용하도록 하겠습니다!

2024-10-14 08:00 UTC, murjune commented on app/src/androidTest/java/nextstep/signup/study/LayoutBasicsTest.kt
> +@Preview(showBackground = true, backgroundColor = 0xFFFFFFFF, device = Devices.PIXEL_4_XL)
이유는 제 에뮬레이터가 PIXEL_4_XL이기 때문이죠 ㅋㅋㅋ 별 뜻은 없습니당

2024-10-14 08:00 UTC, murjune commented on app/src/androidTest/java/nextstep/signup/study/LayoutBasicsTest.kt
> +            .onChildAt(0)
일반적인 테스트에서는 컴포넌트 분리하는 것은 인정이지만, 학습 테스트이기에 간단한 ui의 경우 테스트 내부에 하드코딩된 방식으로 보는 것이 가독성이 좋다고 생각해서 분리하지 않았습니다!

> LMS 요구사항 : 힌트를 참고하여 Preview를 노출시킨다.

이 요구사항은 밑에 PreviewSample 로 이행했습니당

2024-10-14 08:00 UTC, murjune commented on app/src/main/java/nextstep/signup/auth/component/AuthTextField.kt
> +internal fun AuthTextField(
아 이거슨 습관입니다! 해당 컴포넌트가 다른 모듈로 분리될 수 있기 때문에 `internal` 를 붙이는 것을 선호합니당  

빙티가 별로라고 생각하신다면 지우도록 하겠습니다 ㅋㅋㅋ

2024-10-14 08:00 UTC, murjune commented on app/src/main/java/nextstep/signup/auth/component/AuthTextField.kt
> +internal fun AuthTextField(
사실 해당 컴포넌트를 `private` 키워드로 만들까 했지만, IME 액션을 좀 더 커스터마이징할 경우도 있을 것이라 고려하여 오버로딩 함수를 만들었습니다!

2024-10-14 08:00 UTC, murjune commented on app/src/main/java/nextstep/signup/auth/component/AuthTextField.kt
> +@Preview(name = "onClearFocus")
넵 저는 같은 파일에 위치시킵니다!  
xml 을 활용해서 ui를 구현할 때도, 옆에 팔레트를 보면서 하니까 익숙해서 그런 것 같아요 ㅎㅎ  

근데, 더블 모니터가 있으면 파일 분리할 것 같기도?

2024-10-14 08:00 UTC, murjune commented on app/src/main/java/nextstep/signup/auth/component/SignUpForm.kt
> +    Spacer(modifier = Modifier.height(16.dp))
저는 Spacer 를 선호합니다. 기존 xml 방식에서도 Spacer 를 선호하였습니다.  

훨씬 item 사이의 공간을 의미하는 SPacer() 를 활용하는 것이 훨씬 명시적이라 생각하기 때문입니다. 저는 각 컴포넌트의 모서리 부분 여백에만 padding 을 활용합니다 😉

2024-10-14 08:00 UTC, murjune commented on app/src/main/java/nextstep/signup/ui/interaction/ClearFocus.kt
> +        LaunchedEffect(key1 = Unit) {
SIdeEffect 의 경우 해당 컴포저블 함수가 리컴포지션 될때 마다 트리거되기 때문에 선호하지 않습니당 (물론 내부에 if 문을 활용하면 가능하긴 하지만요 ㅋㅅㅋ)  

key 를 활용하는게 더 명시적이라 생각이 들어 LaunchedEffect를 애용합니다 👍

2024-10-14 08:00 UTC, murjune commented on app/src/main/java/nextstep/signup/ui/theme/Theme.kt
> +    onError = Red20
background 는 진짜 앱의 배경을 뜻할 때 사용하고,
surface 는 xml 의 ViewGroup 에 대치되는 컴포저블 (e. Button, Card, Column)에 배경색을 줄 때 사용합니다.  

primary, secondary, tertiary 는 말 그대로 우리 서비스의 Color 를 나타내는 디자인 토큰으로 우리 앱의 Main, Sub, SubSub Color 이지요.

2024-10-14 11:16 UTC, s6m1n commented
질문이 많았는데 오둥이의 생각을 잘 남겨주셨네요~!
다음 미션을 위해 step1,2는 머지하도록 하겠습니다👍

2024-10-14 11:16 UTC, merged