[서기] 회원가입 미션 3, 4단계 제출합니다.
woowacourse/android-signup pull request #24
Opened 2024-10-16 05:13 UTC by Namyunsuk

안녕하세요 하디🦖
3, 4단계도 잘 부탁드려요~!

https://github.com/user-attachments/assets/564e3453-74fa-48e1-b717-be3b44a91f8a

2024-10-17 07:09 UTC, ii2001 requested changes
안녕하세요 서기!
반갑습니댜

현재 실행해보면 입력하기 전에도 빨간색 줄이 뜨던데 혹시 입력을 한후에 빨간색으로 보여주는게 좋다고 생각하는데 어떻게 생각하시나요?? 생각을 공유해주세요!

2024-10-17 07:09 UTC, ii2001 commented on README.md
> +## 3단계 기능 요구 사항
README작성 좋습니다!

2024-10-17 07:09 UTC, ii2001 commented on app/src/androidTest/java/nextstep/signup/fixtures/TestFixture.kt
> +fun FakeSignUpField(
textFixture분리 좋습니다!

2024-10-17 07:09 UTC, ii2001 commented on app/src/androidTest/java/nextstep/signup/fixtures/ui/main/ConfirmedPasswordInputValidationTest.kt
> +    val composeTestRule = createComposeRule()
이 코드를 추가한 이유를 설명해주세요!

2024-10-17 07:09 UTC, ii2001 commented on app/src/androidTest/java/nextstep/signup/fixtures/ui/main/EmailInputValidationTest.kt
> +            FakeSignUpField(
실제 UI를 테스트 해봐야 하는거라고 생각하는데
Fake로 만드신 이유가 있으실까요?
Fake와 실제 UI가 같다고 어떻게 보장할 수 있죠?

2024-10-17 07:09 UTC, ii2001 commented on app/src/androidTest/java/nextstep/signup/fixtures/ui/main/EmailInputValidationTest.kt
> +    fun `이메일_형식이_올바지_않을_경우_에러메시지가_노출된다_2`() {
1,2로 만드는것보단 어떤경우에 에러메세지가 노출된다라고 자세히 적어주셨으면 좋겠습니다!

2024-10-17 07:09 UTC, ii2001 commented on app/src/androidTest/java/nextstep/signup/fixtures/ui/main/PasswordInputValidationTest.kt
> +    fun `비밀번호가_8에서_16자가_아니면_에러메시지가_노출된다_2`() {
마찬가지입니다!

2024-10-17 07:09 UTC, ii2001 commented on app/src/androidTest/java/nextstep/signup/fixtures/ui/main/PasswordInputValidationTest.kt
> +    fun `비밀번호는_영문과_숫자를_포함하지_않으면_에러메시지가_노출된다_2`() {
마찬가지 입니다2

2024-10-17 07:09 UTC, ii2001 commented on app/src/androidTest/java/nextstep/signup/fixtures/ui/main/UserNameInputValidationTest.kt
> +    fun `사용자_이름이_2에서_5자가_아니면_에러메시지가_노출된다_1`() {
마찬가지입니다3

2024-10-17 07:09 UTC, ii2001 commented on app/src/main/java/nextstep/signup/ui/model/SignUpInfo.kt
> +    }
string res로 뺴지 않고 따로 뺄 수 있을까요?

2024-10-21 04:56 UTC, Yunseok-Nam commented on app/src/androidTest/java/nextstep/signup/fixtures/ui/main/ConfirmedPasswordInputValidationTest.kt
> +    val composeTestRule = createComposeRule()
```kotlin
actual fun createComposeRule(): ComposeContentTestRule =
    createAndroidComposeRule<ComponentActivity>()
```
내부 구현체를 보면 ComponentActivity를 시작시키는 것을 볼 수 있습니다. 그리고 `composeTestRule.setContent`를 통해 안에 들어갈 UI를 설정할 수 있습니다!
즉, 테스트에 필요한 환경을 세팅하기 위해 추가한 코드입니다!

그리고 기존에 만들어둔 Activity를 가져오고 싶으면 아래와 같이 사용할 수도 있겠네요!
```kotlin
val composeTestRule = createAndroidComposeRule<MainActivity>()
```

2024-10-21 07:53 UTC, Namyunsuk commented on app/src/androidTest/java/nextstep/signup/fixtures/ui/main/EmailInputValidationTest.kt
> +            FakeSignUpField(
앗 그렇네요!
실제 컴포넌트를 통해 테스트를 하도록 수정했습니다!
[70c2445](https://github.com/woowacourse/android-signup/pull/24/commits/70c24451c6c619710c5190387a2e18e5e7ea36a9)

2024-10-21 07:54 UTC, Namyunsuk commented on app/src/androidTest/java/nextstep/signup/fixtures/ui/main/EmailInputValidationTest.kt
> +    fun `이메일_형식이_올바지_않을_경우_에러메시지가_노출된다_2`() {
반영했습니다!!
[c9efae6](https://github.com/woowacourse/android-signup/pull/24/commits/c9efae6ed52968a70a0c52c3ec59ad4870794669)

2024-10-21 07:55 UTC, Namyunsuk commented on app/src/main/java/nextstep/signup/ui/model/SignUpInfo.kt
> +    }
훔... 문자열 리소스로 분리하는 법 말고는 떠오르지 않더라고요...ㅠㅠ
그래서 일단은 문자열 리소스로 분리했습니다..!
혹시 더 좋은 방법이 있으면 제안해주시면 감사하겠습니당😀

2024-10-22 02:25 UTC, ii2001 commented on app/src/main/java/nextstep/signup/ui/model/SignUpInfo.kt
> +    }
아! 이거 제가 상수화 말고 string으로 빼면 어떠냐고 물어보려고 했던건데 질문이 이상하게 갔네요.. ㅎㅎ 혼란을 주어서 죄송합니다

2024-10-22 02:26 UTC, ii2001 commented
별도 객체들로 로직을 다 옮겨주시고 체계화 시켜주신것 같아서!
원래 리뷰드릴 내용들이 사라졌네요.. ㅎㅎ
그래서 이만 머지 하겠습니다!
리뷰하면서 많이 배웠습니다 감사합니다.

2024-10-22 04:58 UTC, merged