[심지] 회원가입 미션 3, 4단계 제출합니다.
woowacourse/android-signup pull request #35
Opened 2024-10-18 05:27 UTC by sh1mj1

안녕하세요 
# 🐊

이번 주는 여러 예상치 못한 일정이 많아서 좀 늦었네요.

(선택사항) Sign up 버튼을 클릭하면 회원가입 완료 스낵바가 노출된다.
와 SignUpScreenTest 를 제외하고 모두 구현 완료했습니다.

`PreviewParameter` 를 통해 여러 입력 상황에서의 프리뷰를 만들었으며, 테스트 코드 또한 만들었습니다.

| UserName  | Email  | Password  | PasswordConfirm  |
|---|---|---|---|
| <img width="622" alt="image" src="https://github.com/user-attachments/assets/35c918ed-db87-47cf-a782-19767ca2c6d2">  | <img width="628" alt="image" src="https://github.com/user-attachments/assets/8d1a4e5c-5a4f-4c7e-87c3-a2fbc4da5e3d">  |  <img width="639" alt="image" src="https://github.com/user-attachments/assets/4bd62e46-2de6-4955-8e33-b1f6523fab46"> | <img width="628" alt="image" src="https://github.com/user-attachments/assets/e709592c-6c8a-485a-9a3f-946d08805190">  |

여러 파라미터에 대해 테스트 코드를 돌리지 않아도 UI 결과를 바로 확인할 수 있는게 편하더라구요~

다음 PR 에서는 선택 사항을 완료하고, Recomposition 을 최소화하도록 만들어보려고 합니다.

잘 부탁드립니다 악어!~

2024-10-19 14:22 UTC, Hogu59 requested changes
심지 안녕하세요!

바쁜 와중에도 높은 완성도로 구현해주셨군요!
테스트 케이스나 프리뷰로 자세하게 구분해주신 부분 상당히 인상 깊었습니다. 💯 💯 

코드를 보며 몇가지 궁금한 점들을 남겨두었습니다!
답변 남겨주시면 감사하겠습니다! 👍 👍 

요즘 날씨도 춥고 여러모로 바쁜 시간인 것 같은데, 남은 기간동안도 파이팅입니다! 💪

2024-10-19 14:22 UTC, Hogu59 commented on README.md
> +- [x] 테스트 가능한 부분과 테스트하기 힘든 부분을 분리해 테스트 가능한 부분에 대해서만 테스트를 진행한다.
README 작성 굿입니다! 👍

2024-10-19 14:22 UTC, Hogu59 commented on app/src/androidTest/java/nextstep/signup/presentation/signup/EmailTextFieldKtTest.kt
> +        // given
given 이라기 보다는 when에 가깝다고 보여요.
given 절은 애초에 위의 setup() 에서 진행한 것 같다고 생각합니다.

심지가 생각하는 given, when, then의 구분점은 어떤건가요?

2024-10-19 14:22 UTC, Hogu59 commented on app/src/androidTest/java/nextstep/signup/presentation/signup/PasswordConfirmTextFieldKtTest.kt
> +                modifier = Modifier.testTag("test"),
오 이런식으로 테스트 태그를 만들수도 있군요! 💯

2024-10-19 14:22 UTC, Hogu59 commented on app/src/main/java/nextstep/signup/domain/Email.kt
> +    data object InvalidNameFormat : Failure
결과를 Sealed interface로 관리하셨군요!
이렇게 구현하신 이유가 있었을까요?

2024-10-19 14:22 UTC, Hogu59 commented on app/src/main/java/nextstep/signup/domain/PasswordConfirm.kt
> +value class PasswordConfirm(val content: String) {
data class 와 value class의 구분 기준은 어떻게 되나요?
두가지 형식이 섞여 있어서 궁급합니다!

2024-10-19 14:22 UTC, Hogu59 commented on app/src/main/java/nextstep/signup/domain/UserName.kt
> +        private val NAME_RANGE = MIN_NAME_LENGTH..MAX_NAME_LENGTH
이렇게 하신 이유는 regex로 하는것보다 더 유용하다고 생각해서 였을까요? 💭

2024-10-19 14:22 UTC, Hogu59 commented on app/src/test/java/nextstep/signup/domain/UserNameTest.kt
> +    @ValueSource(strings = ["t", "a", "sdfsfeie", "fkskdie"])
오... Junit5 성공하셨군요...
저는 실패했었는데, 잘 가져가겠습니다ㅋㅋㅋ

2024-10-19 14:22 UTC, Hogu59 commented on app/src/test/java/nextstep/signup/domain/UserNameTest.kt
> +    @ValueSource(strings = ["t", "a", "sdfsfeie", "fkskdie"])
![image](https://github.com/user-attachments/assets/e10a81b1-bdf0-48c3-93ff-67c5cd8617ec)

2024-10-19 14:22 UTC, Hogu59 commented on app/src/main/java/nextstep/signup/presentation/signup/EmailTextField.kt
> +    )
이런식으로 preview를 다양한 케이스로 쉽게 볼 수 있군요!
 Preview와 UI 테스트를 각각 어떤 상황에서 활용하시는 편이신가요? 심지의 기준이 궁금합니다!

2024-10-20 10:42 UTC, sh1mj1 commented on app/src/androidTest/java/nextstep/signup/presentation/signup/EmailTextFieldKtTest.kt
> +        // given
저도 악어의 말에 동의합니다!!

[제가 test 코드 작성시에 Live Template 으로 만들어둔 것](https://creampuffy.tistory.com/174) 때문에 given 으로 작성되었네요! ㅎㅎ

2024-10-20 10:48 UTC, sh1mj1 commented on app/src/androidTest/java/nextstep/signup/presentation/signup/EmailTextFieldKtTest.kt
> +        // given
저도 마틴 파울러가 설명한 given, when, then 의 구분과 크게 다르지 않습니다.

Given: the state of the world before you begin the behavior you're specifying in this scenario. (pre-conditions)
When: behavior that you're specifying.
Then: the changes you expect due to the specified behavior.

2024-10-20 10:52 UTC, sh1mj1 commented on app/src/main/java/nextstep/signup/domain/Email.kt
> +    data object InvalidNameFormat : Failure
저는 회원가입을 할 때 Email 과 같은 객체의 유효성은 뷰가 아닌 모델의 책임이라고 생각했습니다.
그런데 어떠한 유효성을 위반하는지에 따라 뷰에서 표시되는 에러 메시지가 달라집니다.

저는 모델에서 이러한 유효성 실패를 Result 를 구현하는 객체들을 리턴하는 것으로 하고, 
뷰에서 Result 에 따라 에러 메시지를 정해주었습니다.

이렇게 하면, 책임이 어느정도 분리될 것 같았습니다.

2024-10-20 10:55 UTC, sh1mj1 commented on app/src/main/java/nextstep/signup/domain/UserName.kt
> +        private val NAME_RANGE = MIN_NAME_LENGTH..MAX_NAME_LENGTH
Regex 로 문자열에 대해 검증하는 것은 꽤 비용이 많이 드는 작업입니다.
문자열 길이만을 먼저 검사하고, 유효하지 않은 길이라면, 빠르게 실패하거나 false 를 리턴할 수 있습니다.

2024-10-20 10:56 UTC, sh1mj1 commented on app/src/test/java/nextstep/signup/domain/UserNameTest.kt
> +    @ValueSource(strings = ["t", "a", "sdfsfeie", "fkskdie"])
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
![image](https://github.com/user-attachments/assets/9a48d51b-9b76-4bc5-b23d-5bc6f0681950)

2024-10-20 11:03 UTC, sh1mj1 commented on app/src/main/java/nextstep/signup/presentation/signup/EmailTextField.kt
> +    )
이번 미션을 하면서 만든 어느정도 기준입니다.

괄호는 더 중요한 곳이 크도록 정리했습니다.

**굉장히 중요한 UI 에 대해서**  -> **UI Test 코드 > Preview** 
종종 Rebuild Project 를 하지 않으면 Preview 가 잘못되어서 나타나는 경우가 있기 때문입니다.

미션의 경우처럼 `when` 이 다양하게 달라질 때 다양한 다른 UI 를 보여줄 경우 -> **UI Test 코드 < Preview**
UI 테스트 코드를 일일이 작성하는 것보다 한 눈에 볼 수 있어 더욱 편합니다.

2024-10-22 08:36 UTC, sh1mj1 commented
안녕하세요~ 
악어 리뷰 반영하고 피드백에 코멘트 남겼습니다.

- [x] recomposition study 테스트
- [x] SignupScreen 테스트가 가능한가?
- [x] recomposition 프로덕션에 적용

악어 그런데 제가 재미있는 것을 발견했답니다!

https://github.com/user-attachments/assets/24867c38-b5b0-444c-939a-4a273e781c51

이렇게 TextField 에 텍스트를 하나쓸 때마다 labelText 
<img width="518" alt="image" src="https://github.com/user-attachments/assets/b73005c9-c397-4257-bb95-a5c128b985ab">
number of times this composable has been recomposed 가 8이나 9 씩 올라간답니다!
신기하죠~

2024-10-22 17:31 UTC, Hogu59 commented
> number of times this composable has been recomposed 가 8이나 9 씩 올라간답니다!
> 신기하죠~

그... 기능인거죠...?ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-10-24 16:17 UTC, Hogu59 approved these changes
심지 안녕하세요!

그동안 미션 구현하시느라 수고 많으셨습니다!
리컴포지션에 대한 학습을 열심히 진행해주신 것 같아요! 👍 👍 

이미 잘 구현해주셨어서 이만 머지하도록 하겠습니다!
데모데이 즐겁게 보내시고, 버퍼기간동안도 재밌게 학습하는 심지가 되길 바라겠습니다! 😄 

수고 많았습니다! 🥇

2024-10-24 16:17 UTC, merged