[에디] 회원가입 미션 1, 2단계 제출합니다.
woowacourse/android-signup pull request #4
Opened 2024-10-08 19:30 UTC by junjange

췤췤 안녕하세요! 🫡
잘 부탁드립니다~~

# 구현 사항
- 학습 테스트 진행
- 회원가입에 필요한 컴포넌트 구현
- 회원가입 뷰 구현

<img width="40%" src="https://github.com/user-attachments/assets/00e4b59e-673b-4e67-a4b0-922905d0497a">

2024-10-09 19:17 UTC, chaehyuns requested changes
전반적으로 코드 구성이 너무 깔끔합니다~ 💯
에디 코드를 보면서 많이 배웠습니다! ㅎㅎ
그리고 제가 컴포즈에 대해서 무지하기 때문에 리뷰가 조금 걱정이 되네요 🥲
앞으로도 잘부탁드려요 에디 🐱

2024-10-09 19:17 UTC, chaehyuns commented on app/src/main/java/nextstep/signup/ui/MainScreen.kt
> +        listOf(
list를 사용해서 입력 필드의 상태를 관리했네요.
개인마다의 생각이 다를 수 있겠지만, 저는 각각의 처리 방식이 달라질 수 있는 상황들에 대비하기 어렵고 가독성이 떨어질 수 있다고 생각합니다.
각각의 필드들을 개별적으로 관리하는 것은 어떤가요?

```
val username = remember { mutableStateOf("") }
val email = remember { mutableStateOf("") }
val password = remember { mutableStateOf("") }
val confirmPassword = remember { mutableStateOf("") }
```

꼭 반영을 해야하는 리뷰는 아니며 에디가 생각하는 방향으로 구현을 해도 좋습니다!

2024-10-09 19:17 UTC, chaehyuns commented on app/src/androidTest/java/nextstep/signup/LayoutBasicsTest.kt
> +// 3. Preview의 interactive 모드를 활용하여 버튼을 클릭해본다.
필요없는 주석은 삭제를 해도 좋을것 같아요!

2024-10-09 19:17 UTC, chaehyuns commented on app/src/androidTest/java/nextstep/signup/LayoutBasicsTest.kt
> +            .assert(hasText("깜포즈"))
test를 작성하면서 "깜포즈"부분에 오타가 날 수도 있고 의도가 불명확해질 수 있다고 생각합니다.
TestFixture을 사용하거나 상수화를 한다면 테스트에서 전달하고 싶은 의도를 더 명확하게 전달할 수 있을 것 같아요~

2024-10-09 19:17 UTC, chaehyuns commented on app/src/androidTest/java/nextstep/signup/LayoutBasicsTest.kt
> +            enabled.value = !enabled.value
불필요한 상태 변화가 일어날 수 있을 것 같습니다!

```
Button(
    onClick = {
        if (enabled.value != false) {
            enabled.value = false
        }
    },
    enabled = enabled.value,
)
```
이런식으로 현재 상태와 새로운 상태가 다른 경우에만 상태를 업데이트하는 조건을 주면 더 좋을 것 같습니다!

2024-10-09 19:17 UTC, chaehyuns commented on app/src/main/java/nextstep/signup/componet/CustomTextField.kt
> +            TextFieldDefaults.colors(
매번 TextFieldDefaults.colors() 를 호출하고 있네요.
   ```
 val textFieldColors = remember {
        TextFieldDefaults.colors(
            focusedIndicatorColor = Blue50,
            focusedLabelColor = Blue50,
            cursorColor = Blue50,
        )
    }
```

이런식으로 선언을 해준다면 첫 실행 시에만 계산되고 이후 재구성 시에는 재사용할 수 있을 것 같아요~~

2024-10-09 19:17 UTC, chaehyuns commented on app/src/main/java/nextstep/signup/componet/CustomTextField.kt
> +fun CustomTextField(
매개변수를 사용한 재사용성 아주 좋아요~ 👍🏻

2024-10-09 19:17 UTC, chaehyuns commented on .editorconfig
> +# Ktlint rules for Kotlin files
컴포즈 ktlint 적용 좋아요~

2024-10-10 02:07 UTC, junjange commented on app/src/androidTest/java/nextstep/signup/LayoutBasicsTest.kt
> +// 3. Preview의 interactive 모드를 활용하여 버튼을 클릭해본다.
네네!

2024-10-10 02:22 UTC, junjange commented on app/src/androidTest/java/nextstep/signup/LayoutBasicsTest.kt
> +            enabled.value = !enabled.value
헉 그러네요! 버튼이 활성화 되어있을 때만 눌릴 수 있게 해야겠군요!

2024-10-10 04:08 UTC, junjange commented on app/src/androidTest/java/nextstep/signup/LayoutBasicsTest.kt
> +            .assert(hasText("깜포즈"))
네네!!

2024-10-10 04:34 UTC, junjange commented on app/src/main/java/nextstep/signup/componet/CustomTextField.kt
> +            TextFieldDefaults.colors(
```kotlin
@Composable
inline fun <T> remember(
    key1: Any?,
    crossinline calculation: @DisallowComposableCalls () -> T
): T {
    return currentComposer.cache(currentComposer.changed(key1), calculation)
}


@Composable
fun colors(
      focusedTextColor: Color = Color.Unspecified,
      unfocusedTextColor: Color = Color.Unspecified,
      disabledTextColor: Color = Color.Unspecified,
      errorTextColor: Color = Color.Unspecified,
      // ...


``` 
`remember` 메서드에서는 `colors`라는 `Composable`을 호출할 수 없습니다!! `remember`는 상태를 기억하기 위한 함수로, `calculation` 파라미터 안에서는 일반적인 함수나 람다만 허용됩니다. 따라서 `colors`와 같은 `Composable`을 직접 호출할 수 없습니다!

2024-10-10 07:27 UTC, junjange commented on app/src/main/java/nextstep/signup/ui/MainScreen.kt
> +        listOf(
가독성과 코드의 간결함을 모두 잡으려 했지만,,, 너무 어려워서 결국 가독성을 우선시 하기로 했습니다!
채채의 의견을 반영해 코드를 개선해봤습니다!!
d2684d400b9ebab659a470da70ca7bf971e45ab9

2024-10-11 07:01 UTC, chaehyuns approved these changes
에디 제 리뷰 사항을 꼼꼼히 반영해주셨네요 👍🏻
다음 단계도 화이팅 해보아요!!!

2024-10-11 07:01 UTC, merged