[예니] 회원가입 미션 1, 2단계 제출합니다.
woowacourse/android-signup pull request #7
Opened 2024-10-09 09:29 UTC by JoYehyun99

안녕하세요 해나! 😊
컴포즈 처음 해봐서 모르는게 많습니다,,, 🥲 
특히 Composable 함수를 분리하는 기준이 감이 잘 안잡혀요,,,
해나는 어떤식으로 분리했는지 궁금하네요! ㅎㅎ

이번 미션 잘 부탁드립니당 🙇‍♀️🙇‍♀️

2024-10-11 04:28 UTC, hxeyexn requested changes
안녕하세요! 예니~
회원가입 미션을 너무 잘 구현해주셨네요!
리뷰가 늦었네요..! 죄송합니다 🥹 양해해주셔서 감사해요!!
코멘트 몇개 남겨두었으니 확인 부탁드려요~ 

2024-10-11 04:28 UTC, hxeyexn commented on app/build.gradle.kts
> +    implementation(libs.androidx.material3)
61번째 줄에 이미 있어서 제거해도 될 것 같아요~ 
Lms에도 이미 추가되어있다고 명시되어 있네요!
<img width="843" alt="image" src="https://github.com/user-attachments/assets/2ee29dd3-062c-4473-8538-649e3873684b">

2024-10-11 04:28 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/MainActivity.kt
>                  Surface(
`Surface`와 `Scaffold`의 차이점은 무엇일까요?

2024-10-11 04:28 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/MainActivity.kt
> +            ),
Typography를 활용해보는 건 어떨까요?

2024-10-11 04:28 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/MainActivity.kt
> +        placeholder = { Text(text = title) },
placeHolder를 지정하신 이유가 궁금합니다!

2024-10-11 04:28 UTC, hxeyexn commented on app/src/androidTest/java/nextstep/signup/LayoutBasicsTest.kt
> +    }
SignupTheme은 없어도 될 것 같아요~
주석 처리 대신 Composable 별로 Preview를 만들어도 괜찮을 것 같아요!
아니면 Column을 이용해서 여러 Composable를 한번에 미리보기해보는 것도 좋을 것 같아요!

2024-10-11 04:28 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/MainActivity.kt
> +            KeyboardType.Password,
KeyboardType도 지정 너무 좋네요 😎

2024-10-11 04:28 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/MainActivity.kt
> +fun Greeting(
지금은 화면이 회원가입 하나뿐이지만 다른 화면이 생긴다면 해당 Greeting을 재활용해야 하는 일이 생길 것 같아요.
Greeting이라는 네이밍 대신 범용적으로 쓸 수 있는 네이밍으로 변경해보는 건 어떨까요?

2024-10-11 04:28 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/MainActivity.kt
> +fun SubmitButton(
Button 역시도 다른 화면이 생긴다면 SubmitButton을 재활용해야 하는 일이 생길 것 같아요!
범용적으로 쓸 수 있는 네이밍으로 변경해봐도 좋을 것 같아요~

2024-10-11 04:28 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/MainActivity.kt
>  class MainActivity : ComponentActivity() {
Greeting, InputText, SubmitButton을 다른 화면에서도 사용할 수 있도록 별도의 파일에 분리하는 건 어떨까요?

2024-10-11 04:28 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/MainActivity.kt
> 특히 Composable 함수를 분리하는 기준이 감이 잘 안잡혀요,,,
해나는 어떤식으로 분리했는지 궁금하네요! ㅎㅎ

저는 아래와 같이 xml에서 style을 정의하는 기준으로 Composable 함수를 분리해보려 했습니다!
Composable 함수 분리도 재활용을 위한 거라고 생각해서 style과 비슷하다는 생각이 들었어요!!
```xml
    <style name="ButtonStyle">
        <item name="android:layout_width">0dp</item>
        <item name="android:layout_height">wrap_content</item>
        <item name="android:minWidth">0dp</item>
        <item name="android:minHeight">0dp</item>
        <item name="android:paddingVertical">14dp</item>
        <item name="android:stateListAnimator">@null</item>
        <item name="android:textAppearance">@style/Typography.Title3</item>
    </style>
```
저도 Compose가 처음이라 아직 기준이 명확히 잡히지는 않아서 참고만 해주세요 ㅎㅎ

2024-10-11 05:23 UTC, JoYehyun99 commented on app/src/main/java/nextstep/signup/MainActivity.kt
> +        placeholder = { Text(text = title) },
텍스트 필드에 아무것도 입력하지 않았을 때 보여지는 텍스트가 `placeholder` 의 역할인 줄 알았는데, 
`label` 이 그 역할도 해주네요 ,,ㅎㅎ

2024-10-11 06:13 UTC, JoYehyun99 commented on app/src/main/java/nextstep/signup/MainActivity.kt
> xml에서 style을 정의하는 기준

저도 동의합니다!👍 저도 계속 여러 방법으로 분리해보다 보니
xml에서 style 를 지정하는 느낌과 비슷하다고 생각이 들었네요 ㅎㅎㅎ

2024-10-11 07:05 UTC, hxeyexn commented
<img width="1150" alt="image" src="https://github.com/user-attachments/assets/053f944c-26e2-48cb-aabc-aed957219cdd">

그리고 ktlintcheck가 통과하지 않고 있는 것 같은데 확인 부탁드려요!

2024-10-11 07:33 UTC, JoYehyun99 commented on app/src/main/java/nextstep/signup/MainActivity.kt
>                  Surface(
`Scaffold` 은 앱의 전체 레이아웃을 구성하는데 사용되고 (topbar 나 bottombar 등) 
`Surface` 는 개별 UI 컴포넌트 요소에 대한 디자인 (boader, background, color 등) 을 위한 요소 입니다 🤔

만약 해당 화면에 앱바나 바텀바와 같은 앱 전체적인 레이아웃에 대해 요구사항이 존재한다면, `Scaffold` 를 사용하는 것이 좋을 것 같아요!

2024-10-12 07:41 UTC, hxeyexn commented
> 텍스트 필드에 아무것도 입력하지 않았을 때 보여지는 텍스트가 placeholder 의 역할인 줄 알았는데,
label 이 그 역할도 해주네요 ,,, 😅

속성이 어떤 역할인지 헷갈릴 때는 [Material Design3 Components](https://m3.material.io/components) 를 활용해보세요! 모든 Components와 관련된 속성 설명이 잘 되어있어서 view 구현할 때 도움이 많이 되더라고요!

2024-10-12 07:47 UTC, hxeyexn approved these changes
안녕하세요 예니! 🐰
리뷰 반영을 잘 해주셨네요~ 

원활한 3, 4단계 진행을 위해 1, 2단계는 이만 머지하도록 하겠습니다!
코멘트 몇개 더 남겨두었으니 확인 부탁드려요!

3, 4단계도 화이팅입니다!! 😎

2024-10-12 07:47 UTC, hxeyexn commented on app/src/androidTest/java/nextstep/signup/LayoutBasicsTest.kt
> +        }
ButtonComposable이 직접 상태를 관리하는 대신  stateless 하게 변경해주셨네요! 👍

2024-10-12 07:47 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/MainActivity.kt
> +fun SignUpPreview() {
Preview는 다른 화면에서 참조할 일이 없어서  private 키워드를 붙여도 좋을 것 같아요!

2024-10-12 07:47 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/MainActivity.kt
>                  Surface(
<img width="642" alt="image" src="https://github.com/user-attachments/assets/b7a4d178-47a4-4b6c-a8b2-68a19d58f08a">

`Scaffold.kt`

<img width="662" alt="image" src="https://github.com/user-attachments/assets/e2dd45c8-8e18-46a8-ba47-6ee908371748">

`Surface.kt`

맞아요! `Scaffold`는 Material Design의 레이아웃 구조(topBar, bottomBar, floatingActionButton 등)를 구현하는 데 사용되고, 여러 Material Component를 조합해서 화면을 구성할 수 있는 API를 제공해줘요! 

`Surface`는 UI 요소의 배치 및 모양을 제어하는 컨테이너를 생성하는 데 사용되며 Clipping, Bolders, Background, Content color 등을 설정하여 시각적 일관성을 유지해줍니다!

2024-10-12 07:47 UTC, hxeyexn commented on app/src/main/java/nextstep/signup/ui/component/TextFields.kt
> +        label = { Text(text = title) },
>텍스트 필드에 아무것도 입력하지 않았을 때 보여지는 텍스트가 placeholder 의 역할인 줄 알았는데,
label 이 그 역할도 해주네요 ,,, 😅

속성이 어떤 역할을 하는지 헷갈릴 때는 [Material Design3 Components](https://m3.material.io/components) 를 활용해보세요! 모든 Components와 관련된 속성 설명이 잘 되어있어서 view 구현할 때 도움이 많이 되더라고요!

2024-10-12 07:47 UTC, merged